__include__: [
  '../dataset/coco_mot_detection.yml',
  '../runtime.yml',
  './include/dataloader_mot.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

model: RTDETR_MOT
criterion: SetCriterion
postprocessor: RTDETRPostProcessor

RTDETR_MOT:
  backbone: PResNet
  encoder: HybridEncoder
  decoder: RTDETRTransformerMOT
  multi_scale: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800]
  criterion: CriterionMOT

PResNet:
  depth: 101


HybridEncoder:
  # intra
  hidden_dim: 384
  dim_feedforward: 2048


RTDETRTransformerMOT:
  feat_channels: [384, 384, 384]

CriterionMOT:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2,}
  losses: ['vfl', 'boxes', ]
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    use_focal_loss: True
    alpha: 0.25
    gamma: 2.0

optimizer:
  type: AdamW
  params: 
    - 
      params: 'backbone'
      lr: 0.000001

output_dir: 'rtdetr_101vd_6x_mot_v3'

epoches: 100

mode_train: 'mot'
